/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registration;

import registereduser.regisuser;
import java.sql.*;

/**
 *
 * @author root1
 */
public class regisform extends javax.swing.JFrame {

    /**
     * Creates new form regisform
     */
    public regisform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jname1 = new javax.swing.JTextField();
        jmale1 = new javax.swing.JRadioButton();
        jfemale1 = new javax.swing.JRadioButton();
        jmobile1 = new javax.swing.JTextField();
        jday1 = new javax.swing.JComboBox<>();
        jmonth1 = new javax.swing.JComboBox<>();
        jyear1 = new javax.swing.JComboBox<>();
        jemail1 = new javax.swing.JTextField();
        jpass1 = new javax.swing.JPasswordField();
        submit2 = new javax.swing.JButton();
        reset2 = new javax.swing.JButton();
        jterm1 = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtext1 = new javax.swing.JTextArea();
        jregis1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 128, 128));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(86, 204, 84), 6));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 48)); // NOI18N
        jLabel1.setText("REGISTRATION FORM");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel2.setText("NAME");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel3.setText("GENDER");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel4.setText("DATE OF BIRTH");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel5.setText("MOBILE NUMBER");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel6.setText("EMAIL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 448, -1, 20));

        jLabel7.setFont(new java.awt.Font("Ubuntu Light", 1, 18)); // NOI18N
        jLabel7.setText("PASSWORD");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 100, -1));
        jPanel1.add(jname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 168, 200, 30));

        jmale1.setText("MALE");
        jPanel1.add(jmale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));
        buttonGroup1.add(jmale1);

        jfemale1.setText("FEMALE");
        jPanel1.add(jfemale1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, -1));
        buttonGroup1.add(jfemale1);
        jPanel1.add(jmobile1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 200, 30));

        jday1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"} ));
        jday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jday1ActionPerformed(evt);
            }
        });
        jPanel1.add(jday1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jmonth1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr","May","Jun","July","Aug","Sep","Oct","Nov","Dec" }));
        jmonth1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmonth1ActionPerformed(evt);
            }
        });
        jPanel1.add(jmonth1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jyear1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993","1994","1995","1996","1997","1998","1999","2000" }));
        jPanel1.add(jyear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));
        jPanel1.add(jemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 200, 30));
        jPanel1.add(jpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 550, 200, 30));

        submit2.setText("SUBMIT");
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        jPanel1.add(submit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 100, 40));

        reset2.setText("RESET");
        reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset2ActionPerformed(evt);
            }
        });
        jPanel1.add(reset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 90, 40));

        jterm1.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        jterm1.setText("Accept terms and condition");
        jPanel1.add(jterm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        jtext1.setColumns(20);
        jtext1.setRows(5);
        jScrollPane1.setViewportView(jtext1);
        jtext1.setEditable(false);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 162, 280, 460));

        jregis1.setText("LOGIN AS REGISTERED USER");
        jregis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jregis1ActionPerformed(evt);
            }
        });
        jPanel1.add(jregis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 650, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmonth1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmonth1ActionPerformed
        // TODO add your handling code hereab: 
        
        
    }//GEN-LAST:event_jmonth1ActionPerformed

    private void jday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jday1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jday1ActionPerformed

    private void reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset2ActionPerformed
        // TODO add your handling code here:
        jname1.setText(null);
       
       
        jday1.setSelectedIndex(0);
        jmonth1.setSelectedIndex(0);
        jyear1.setSelectedIndex(0);
        jemail1.setText(null);
        jmobile1.setText(null);
        jpass1.setText(null);
        buttonGroup1.clearSelection();
        jterm1.setSelected(false);
         jtext1.setText(null);
        
        
    }//GEN-LAST:event_reset2ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
        // TODO add your handling code here:
        String ch = evt.getActionCommand();
        if(ch== "SUBMIT")
        {
            if(jterm1.isSelected())
            {
                String name = jname1.getText();
                String email = jemail1.getText();
                String mobile= jmobile1.getText();
                String gen = "Male";
                String pass1 = jpass1.getText();
                if(jfemale1.isSelected())
                {
                    gen = "Female";
                    
                }
                
                String date = (String)jday1.getSelectedItem();
                String  mon = (String)jmonth1.getSelectedItem();
                 String  yr = (String)jyear1.getSelectedItem();
                 
                 
            jtext1.setText("\n\nName:"+name+"\nEmail:"+email+"\nMobile:"+mobile+"\nDate Of Birth"+" "+date+" "
                            +mon+" "+yr+"\n Gender:"+gen+"\npassword:"+pass1+"\n\n");
            
            
            try
            {   Connection conn = null;
            
                try
                {
                  Class.forName("com.mysql.cj.jdbc.Driver");
                  jtext1.setText("Driver Loaded");
                  
                }
                
                catch(ClassNotFoundException e)
            {
                jtext1.setText("Exception:" +e.getMessage());
            }
               
                 conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/shivam?setTimezone=true&serverTimezone=UTC" ,"root","root");
                 jtext1.setText("Connection established");
                
                String sql = "insert into dataitem(name,gender,day,month,year,mobile,email,pass)values(?,?,?,?,?,?,?,?)";
                
                PreparedStatement st = conn.prepareStatement(sql);
                
                st.setString(1, name);
                st.setString(2, gen);
                st.setString(3, date);
                st.setString(4, mon);
                st.setString(5, yr);
                st.setString(6, mobile);
                st.setString(7, email);
                st.setString(8, pass1);
                
                st.executeUpdate();
                
                jtext1.setText("Registration Successful");
                st.close();
                conn.close();
            }
            
            
            catch(SQLException e)
            {
                jtext1.setText("SQL Exception:" +e.getMessage());
            }
           
            
            
          
           
            
        
            }   
              else
            {
                jtext1.setText("Please Agree Our Term And Condition");
                
            }
            }   
         else
        {
            jname1.setText(null);
            jmale1.setText(null);
            jfemale1.setText(null);
            jday1.setSelectedIndex(0);
            jmonth1.setSelectedIndex(0);
            jyear1.setSelectedIndex(0);
            jemail1.setText(null);
            jmobile1.setText(null);
            jpass1.setText(null);
            buttonGroup1.clearSelection();
             jtext1.setText(null);
            
            jterm1.setSelected(false);
        }
        
        
        
    }//GEN-LAST:event_submit2ActionPerformed

    private void jregis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jregis1ActionPerformed
        // TODO add your handling code here:
        new regisuser().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jregis1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regisform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regisform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jday1;
    private javax.swing.JTextField jemail1;
    private javax.swing.JRadioButton jfemale1;
    private javax.swing.JRadioButton jmale1;
    private javax.swing.JTextField jmobile1;
    private javax.swing.JComboBox<String> jmonth1;
    private javax.swing.JTextField jname1;
    private javax.swing.JPasswordField jpass1;
    private javax.swing.JButton jregis1;
    private javax.swing.JCheckBox jterm1;
    private javax.swing.JTextArea jtext1;
    private javax.swing.JComboBox<String> jyear1;
    private javax.swing.JButton reset2;
    private javax.swing.JButton submit2;
    // End of variables declaration//GEN-END:variables
}
