/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registereduser;
import java.sql.*;
import java.util.InputMismatchException;
import javax.swing.JOptionPane;


/**
 *
 * @author root1
 */
public class regisuser extends javax.swing.JFrame {

    /**
     * Creates new form regisuser
     */
    public regisuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jusername1 = new javax.swing.JTextField();
        jpass1 = new javax.swing.JPasswordField();
        jsubmit2 = new javax.swing.JButton();
        jreset2 = new javax.swing.JButton();
        jexit2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtext3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(42, 176, 26));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(60, 73, 56), 6));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel1.setText("         REGISTERED USER LOGIN");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 770, 60));

        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        jLabel2.setText("NAME");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, -1));

        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 36)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 170, 50));

        jusername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jusername1ActionPerformed(evt);
            }
        });
        jPanel3.add(jusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 210, 40));
        jPanel3.add(jpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 40));

        jsubmit2.setText("SHOW DATA");
        jsubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsubmit2ActionPerformed(evt);
            }
        });
        jPanel3.add(jsubmit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 140, -1));

        jreset2.setText("RESET");
        jreset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jreset2ActionPerformed(evt);
            }
        });
        jPanel3.add(jreset2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, 30));

        jexit2.setText("EXIT");
        jexit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jexit2ActionPerformed(evt);
            }
        });
        jPanel3.add(jexit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 100, 30));

        jtext3.setColumns(20);
        jtext3.setEditable(false);
        jtext3.setRows(5);
        jScrollPane1.setViewportView(jtext3);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 360, 370));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jusername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jusername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jusername1ActionPerformed

    private void jexit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jexit2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_jexit2ActionPerformed

    private void jreset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jreset2ActionPerformed
        // TODO add your handling code here:
        jusername1.setText(null);
        jpass1.setText(null);
        jtext3.setText(null);
    }//GEN-LAST:event_jreset2ActionPerformed

    private void jsubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsubmit2ActionPerformed
        // TODO add your handling code here:
        
        String username = jusername1.getText();
        String password = jpass1.getText();
        String query = "select * from dataitem where name=? && pass=?";
        Connection conn = null;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Drivers loaded");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/shivam?useTimezone=true&serverTimezone=UTC","root","root");
            System.out.println("Connecction Established");
         
            PreparedStatement st = conn.prepareStatement(query);
            st.setString(1,username);
            st.setString(2,password);
            ResultSet rs = st.executeQuery();
            
             
            while(rs.next())
            {
                String name = rs.getString("name");
                String email = rs.getString("email");
                String gender =  rs.getString("gender");
                String mobile = rs.getString("mobile");
                String password1 = rs.getString("pass");
                String gen = rs.getString("gender");
                String date = rs.getString("day");
                String mon = rs.getString("month");
                String yr = rs.getString("year");
                
                jtext3.setText("\n\nName:"+name+"\nEmail:"+email+"\nMobile:"+mobile+"\nDate Of Birth"+" "+date+" "
                            +mon+" "+yr+"\n Gender:"+gen+"\npassword:"+password1+"\n\n");
                
            }
            
            conn.close();
            st.close();
            
            rs.close();
         }
        catch(ClassNotFoundException e)
        {
            System.out.println("Exception:" +e.getMessage());
        }
        catch(SQLException e)
        {
            System.out.println("Connection Error:" +e.getMessage());
            
        }
       
        
        
    }//GEN-LAST:event_jsubmit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regisuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regisuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regisuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regisuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regisuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jexit2;
    private javax.swing.JPasswordField jpass1;
    private javax.swing.JButton jreset2;
    private javax.swing.JButton jsubmit2;
    private javax.swing.JTextArea jtext3;
    private javax.swing.JTextField jusername1;
    // End of variables declaration//GEN-END:variables
}
